import Head from "next/head";
import Image from "next/image";
import Header from "./../components/header";
import Hero from "./../components/hero";
import Categories from "../components/categories";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Hero />
        <Categories />
      </main>
    </div>
  );
}
